### ISSUE TITLE
Can you give a example of using the model in c++

### ISSUE THREAD

**Issue by Ray-0403** [antoinecarme/ml2cpp#34]
Hi, I want to try your method to deploy my ml model in c++. Can you provide some examples of using the saved ml model in c++?

**Comment by antoinecarme** [comment]
hi @Ray-0403 

Thanks for your interest in ml2cpp. I will appreciate any kind of feedback on the use case you are expecting.

ml2cpp is a demo for a model deployment tool in C++. It mainly contains docs or Jupyter notebooks , but not enough to be operational in a user environment.

If you need an equivalent tool , based on SQL, that does not need a specific deployment procedure (just execute the SQL to get the output of the model), please try sklearn2SQL. The SQL can be executed from a C++ code, on an in-process SQLite database.

sklearn2SQL is available as a web service, no code. You can  access it here : 

https://github.com/antoinecarme/sklearn2sql_heroku

A demo script : https://github.com/antoinecarme/sklearn2sql_heroku/blob/master/test_client.py

Some Jupyter notebooks on using sklearn2SQL are available here : 

https://github.com/antoinecarme/sklearn2sql_heroku/tree/master/docs

**Comment by Ray-0403** [comment]
Thank you very much!
